/panther/sterling/local_costmap_builder:
  sub_topic_camera: "/oakd2/oak_d_node/rgb/image_rect_color"
  sub_topic_local_costmap: "/local_costmap/costmap"
  pub_topic_local_costmap: "/sterling/local_costmap"
  pub_topic_local_costmap_hz: 1.0
  model_path: "/root/ros_ws/src/sterling_patern_costmaps/models/"
  # True to run the adapted Patern model, looks for _adapted.pt files in the model folder
  adapted: true
  # True to allow model to label obstacles from terrain
  label_obstacles: false
  homography_matrix:
    - 1.2549033893146113
    - -0.009711844123833758
    - -792.5257569045234
    - -0.0032050245281481844
    - 4.330442285389362
    - -2627.3111389729593
    - -1.2252930562221849e-05
    - 0.0044237916057277196
    - -1.6782341544478678

/sterling/global_costmap_builder:
  sub_topic_local_costmap: "/sterling/local_costmap"
  sub_topic_global_costmap: "/global_costmap/costmap"
  use_maximum: false
