version: '3.8'

services:
  ros:
    build:
      # set the build context to the directory containing build files
      context: ..
      dockerfile: docker/Dockerfile
      ssh:
          - default
    container_name: sterling_patern_costmaps_c
    image: sterling_patern_costmaps_c
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./ros_ws:/ros_ws
    network_mode: host
    stdin_open: true
    tty: true
